package ReverseApp;


/**
* ReverseApp/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverse.idl
* Sunday, 3 May, 2026 10:50:55 PM IST
*/

public interface ReverseOperations 
{
  String reverseString (String str);
} // interface ReverseOperations
