package UppercaseApp;


/**
* UppercaseApp/Uppercase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Uppercase.idl
* Sunday, 3 May, 2026 11:17:57 AM IST
*/

public interface Uppercase extends UppercaseOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Uppercase
