package UppercaseApp;


/**
* UppercaseApp/UppercaseHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Uppercase.idl
* Sunday, 3 May, 2026 11:17:57 AM IST
*/

abstract public class UppercaseHelper
{
  private static String  _id = "IDL:UppercaseApp/Uppercase:1.0";

  public static void insert (org.omg.CORBA.Any a, UppercaseApp.Uppercase that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static UppercaseApp.Uppercase extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (UppercaseApp.UppercaseHelper.id (), "Uppercase");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static UppercaseApp.Uppercase read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_UppercaseStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, UppercaseApp.Uppercase value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static UppercaseApp.Uppercase narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof UppercaseApp.Uppercase)
      return (UppercaseApp.Uppercase)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      UppercaseApp._UppercaseStub stub = new UppercaseApp._UppercaseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static UppercaseApp.Uppercase unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof UppercaseApp.Uppercase)
      return (UppercaseApp.Uppercase)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      UppercaseApp._UppercaseStub stub = new UppercaseApp._UppercaseStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
