package UppercaseApp;


/**
* UppercaseApp/UppercaseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Uppercase.idl
* Sunday, 3 May, 2026 11:17:57 AM IST
*/

public interface UppercaseOperations 
{
  String toUpperCase (String str);
} // interface UppercaseOperations
