package UppercaseApp;

/**
* UppercaseApp/UppercaseHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Uppercase.idl
* Sunday, 3 May, 2026 11:17:57 AM IST
*/

public final class UppercaseHolder implements org.omg.CORBA.portable.Streamable
{
  public UppercaseApp.Uppercase value = null;

  public UppercaseHolder ()
  {
  }

  public UppercaseHolder (UppercaseApp.Uppercase initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = UppercaseApp.UppercaseHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    UppercaseApp.UppercaseHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return UppercaseApp.UppercaseHelper.type ();
  }

}
